import SideBar from "@/components/home/Sidebar";
import Head from "next/head";
import { createContext, useState } from "react";

export const MainCtx = createContext(
  {} as {
    isDarkMode: boolean;
    setDarkMode: React.Dispatch<React.SetStateAction<boolean>>;
    isShowing: boolean;
    setShowing: React.Dispatch<React.SetStateAction<boolean>>;
  }
);

const Home = () => {
  const [isShowing, setShowing] = useState(false); // Showing the sidebar
  const [isDarkMode, setDarkMode] = useState(true); // Dark theme state

  return (
    <>
      <Head>
        <title>Clone GPT - Stiven</title>
        <meta name="description" content="Generated by create-next-app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <MainCtx.Provider
        value={{ isShowing, setShowing, isDarkMode, setDarkMode }}
      >
        <main className="relative flex h-screen w-full overflow-hidden bg-white dark:bg-gray-800">
          {/* Sidebar Layout */}
          <SideBar />

          {/* Main Section */}
          {/* <MainSection /> */}
        </main>
      </MainCtx.Provider>
    </>
  );
};

export default Home;
